# Generated by Django 5.2.4 on 2025-08-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodule',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20, verbose_name='Access Type'),
        ),
        migrations.AddField(
            model_name='notesmodule',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instructor/Doctor'),
        ),
    ]
