# Generated by Django 5.2.4 on 2025-08-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notesmodule_access_type_notesmodule_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notescategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notestopic',
            options={'verbose_name': 'Notes Topic', 'verbose_name_plural': 'Notes Topics'},
        ),
        migrations.AlterUniqueTogether(
            name='notestopic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='modules_count',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='topics_count',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notescategory',
            name='videos_count',
        ),
        migrations.CreateModel(
            name='NotesVideoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topic Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='notes.notescategory')),
            ],
        ),
        migrations.CreateModel(
            name='NotesVideoSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=255, verbose_name='Doctor Name')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration (Seconds)')),
                ('logo', models.ImageField(blank=True, upload_to='video_logos/', verbose_name='Logo')),
                ('free', models.BooleanField(default=True, verbose_name='Is Free')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='notes.notesvideomain')),
            ],
        ),
        migrations.CreateModel(
            name='NotesVideoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='notes.notesvideosub')),
            ],
        ),
        migrations.RemoveField(
            model_name='notestopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notestopic',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='notestopic',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='notestopic',
            name='modules_count',
        ),
        migrations.RemoveField(
            model_name='notestopic',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notestopic',
            name='videos_count',
        ),
    ]
