# Generated by Django 5.2.4 on 2025-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notescategory_options_alter_notestopic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesclinicalcase',
            name='module',
        ),
        migrations.RemoveField(
            model_name='notesflashcard',
            name='module',
        ),
        migrations.RemoveField(
            model_name='notesmcq',
            name='module',
        ),
        migrations.RemoveField(
            model_name='notesmcqoption',
            name='mcq',
        ),
        migrations.AlterUniqueTogether(
            name='notesmodule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notesmodule',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='notesqbank',
            name='module',
        ),
        migrations.RemoveField(
            model_name='notespreviouspapers',
            name='module',
        ),
        migrations.RemoveField(
            model_name='notesvideo',
            name='module',
        ),
        migrations.RemoveField(
            model_name='notesqbankoption',
            name='q_bank',
        ),
        migrations.DeleteModel(
            name='NotesStatistics',
        ),
        migrations.AddField(
            model_name='notesvideoplayer',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=YVxWJaxlJRI', max_length=500, verbose_name='Video URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NotesClinicalCase',
        ),
        migrations.DeleteModel(
            name='NotesFlashCard',
        ),
        migrations.DeleteModel(
            name='NotesMCQ',
        ),
        migrations.DeleteModel(
            name='NotesMCQOption',
        ),
        migrations.DeleteModel(
            name='NotesTopic',
        ),
        migrations.DeleteModel(
            name='NotesPreviousPapers',
        ),
        migrations.DeleteModel(
            name='NotesModule',
        ),
        migrations.DeleteModel(
            name='NotesVideo',
        ),
        migrations.DeleteModel(
            name='NotesQBank',
        ),
        migrations.DeleteModel(
            name='NotesQBankOption',
        ),
    ]
