# Generated by Django 5.2.4 on 2025-08-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notesclinicalcase_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesvideosub',
            name='name',
            field=models.CharField(default='A', max_length=255, verbose_name='Video Title'),
            preserve_default=False,
        ),
    ]
